// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkScope } from "./LinkScope";

export type LinkSchema = { link: string, scope: LinkScope, identifier: string, };
