// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkSchema } from "./LinkSchema";

export type PageSettings = { title: string, css_links: Array<LinkSchema>, js_links: Array<LinkSchema>, };
