// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectConfiguration } from "./ProjectConfiguration";

export type ProjectData = { name: string, uuid: string, app_version: string, configuration: ProjectConfiguration, };
