// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectAssetType } from "./ProjectAssetType";

export type ProjectAsset = { file_type: ProjectAssetType, filename: string, filepath: string, };
