name: Build APP

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x]
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn
        
    - run: yarn 
#     - run: yarn global add @tauri-apps/cli@latest
    - run: yarn tauri info
    - run: yarn tauri build
